config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    get "delete"
    get :like, :dislike, on: :member
    resources :comments
  end

  resources :categories do
    get "delete"
  end

  root to: "posts#index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many   :comments
	belongs_to :category
	validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	respond_to :html,:js

	def index
		@categories = Category.all
		@category   = Category.new
	end

	def new
		@category = Category.new
	end

	def create
		@categories = Category.all
		@category = Category.create(cat_params)
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@categories = Category.all
		@category = Category.find(params[:id])
		@category.update_attributes(cat_params)
	end

	def delete
		@category = Category.find(params[:category_id])
	end

	def destroy
		@categories = Category.all
		@category = Category.find(params[:id])
		@category.destroy
	end

	private

	def cat_params
		params.require(:category).permit(:cat_name, :cat_description)
	end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :html, :js

	def index
		@comments = Comment.all		
	end

	def new
		@comment = Comment.new		
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comments_params)	
		#render nothing: true
	end

	def destroy
		
	end

	private
	def comments_params
		params.require(:comment).permit(:c_author, :c_body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :html, :js

	def index
		@posts = Post.all
		@post = Post.new
		@poster_ip = request.remote_ip
	end

	def show
		@post = Post.find(params[:id])
		@poster_ip = request.remote_ip
	end

	def new
		@post = Post.new
	end

	def create
		@posts = Post.all
		@post = Post.create(post_params)
	end

	def edit
		@post = Post.find(params[:id])		
	end

	def update
		@posts = Post.all
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
	end

	def delete
		@post = Post.find(params[:post_id])
	end

	def destroy
		@posts = Post.all
		@post = Post.find(params[:id])
		@post.destroy
	end

	def like
		@post = Post.find(params[:id])
		@post.increment!(:rating)	
		render 'show'	
	end

	def dislike
		@post = Post.find(params[:id])
		@post.decrement!(:rating)
		render 'show'		
	end

	private
	    def post_params
	    	params.require(:post).permit(:author,:title,:body,:category_id,:category)	    	
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_cat_form.html.erb
<%= form_for @category, remote: true, html: {class: "form-horizontal", style: "display:inline"} do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :cat_name, class: "control-label" %>
      <div class="controls">
      <%= f.text_field :cat_name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :cat_description, class: "control-label" %>
      <div class="controls">
      <%= f.text_area :cat_description %>
      </div> 
    </div>
  </div>
  <div class="modal-footer">
  	<%= f.submit calss: "btn btn-primary" %>
    <%= link_to "Cancel", '#', class: "btn", data: {dismiss: "modal"} %>
  </div>
  <% end %>

app/views/categories/_cat_index.html.erb
<% @categories.each do |cat| %>
	<tr>
		<td><%= cat.cat_name %></td>        		
		<td><%= cat.cat_description %></td>
		<td><%= link_to "Edit", edit_category_path(cat), remote: true, class: "btn btn-success" %></td>
		<td><%= link_to "Delete", category_delete_path(cat), remote: true, class: "btn btn-danger"  %></td>
		<td><%= link_to "Show", category_path(cat), remote: true, class: "btn btn-primary"  %></td>
           
    </tr>
	
<% end %>

app/views/categories/_delete.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3>Delete Category</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @category.cat_name %></b>
</div>
<div class="modal-footer">
	<%= link_to "Yes, delete this category", category_path(@category), method: :delete, remote: true, class: "btn btn-danger" %>
	<%= link_to "No", '#', class: "btn", data: {dismiss: "modal"} %>
</div>
</div>
</div>

app/views/categories/_edit.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3><%= "Editing #{@category.cat_name}" %></h3>
</div>
<%= render 'cat_form' %>
</div>
</div>

app/views/categories/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3> New Category</h3>
    </div>
      <%= render 'cat_form' %>
    </div>
  </div>
</div>

app/views/categories/_save.js.erb
$("ul.errors").html("")
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |message| %>
	$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
    $(".cat-index").html("<%= escape_javascript(render 'cat_index') %>")
    $("#cat-modal").modal("hide")
<% end %>    

app/views/categories/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
    <h3>
      <%= @category.cat_name %>
    </h3>
    </div>
    <div class="modal-body">
      <%= @category.cat_description %>

    </div>
    <div class="modal-footer">
      <%= link_to "Close", '#', class: "btn btn-danger", data: {dismiss: "modal"} %>
    </div>
</div>
</div>

app/views/categories/create.js.erb
<%= render 'save' %>

app/views/categories/delete.js.erb
$("#cat-modal").html("<%= escape_javascript(render 'delete') %>")
$("#cat-modal").modal("show")

app/views/categories/destroy.js.erb
<%= render 'save' %>

app/views/categories/edit.js.erb
$('#cat-modal').html("<%= escape_javascript(render 'edit') %>");
$('#cat-modal').modal("show");

app/views/categories/index.html.erb
<div class="container">
<div class="well">
    
    <%= link_to "New Category", new_category_path, remote: true, class: "btn btn-primary" %>
    <%= link_to "Back", posts_path, class: "btn btn-primary" %>
   
</div>
<div class="new-cat"></div>

<table class="table table-bordered table-striped">
  <thead>
  	<tr>
  		<th>Category Name</th>
      <th>Desription</th>
  		<th>&nbsp;</th>
  		<th>&nbsp;</th>
    </tr>
  </thead>
  <tbody class="cat-index">
  	<%= render 'cat_index' %>
  </tbody>
</table>
</div>
<div id="cat-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true"></div>

app/views/categories/show.js.erb
$('#cat-modal').html("<%= escape_javascript(render 'show') %>");
$('#cat-modal').modal('show');

app/views/categories/update.js.erb
<%= render 'save' %>

app/views/comments/_comment.html.erb
<strong>Author: </strong><%= comment.c_author %><br>
<strong>Comment:</strong><br>
<%= comment.c_body %><br>
<strong>Added at: </strong><%= comment.created_at %><br>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], remote: true) do |f| %>

<div class="control-group">
<%= f.label 'Author' %><br>
<%= f.text_field :c_author %>
</div>

<div class="control-group">
<%= f.label 'Comment' %><br>
<%= f.text_area :c_body %>
</div><br>

<div class="control-group">
<%= f.submit 'Add Comment', class: "btn btn-primary" %>
</div>

<% end %>

app/views/comments/create.js.erb
$('#comments').html("<%= j render @post.comments %>");
$('#comment_c_author').val('');
$('#comment_c_body').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_delete.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3>Delete Post</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @post.title %></b>
</div>
<div class="modal-footer">
	<%= link_to "Yes, delete this post", post_path(@post), method: :delete, remote: true, class: "btn btn-danger" %>
	<%= link_to "No", '#', class: "btn", data: {dismiss: "modal"} %>
</div>
</div>
</div>

app/views/posts/_edit.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3><%= "Editing #{@post.title}" %></h3>
</div>
<%= render 'form' %>
</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true, html: {class: "form-horizontal", style: "display:inline"} do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :author, class: "control-label" %>
      <div class="controls">
      <%= f.text_field :author %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :title, class: "control-label" %>
      <div class="controls">
      <%= f.text_field :title %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :body, class: "control-label" %>
      <div class="controls">
      <%= f.text_area :body %>
      </div> 
    </div>
    <div class="control-group">
      <%= f.label :category, class: "control-label" %>
      <div class="controls">
      <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :cat_name) %>
      </div> 
    </div>
  </div>
  <div class="modal-footer">
  	<%= f.submit calss: "btn btn-primary" %>
    <%= link_to "Cancel", '#', class: "btn", data: {dismiss: "modal"} %>
  </div>
  <% end %>

app/views/posts/_index.html.erb
<% @posts.each do |post| %>
	<tr>
		<td><%= post.author %><br>
        <%= @poster_ip %>
		</td>
		<td><%= post.title %></td>
		<td><%= post.body %></td>
		<td><%= post.rating %></td>
		<td><%= post.category.cat_name %></td>
		<td><%= link_to "Edit", edit_post_path(post), remote: true, class: "btn btn-success" %></td>
		<td><%= link_to "Delete", post_delete_path(post), remote: true, class: "btn btn-danger"  %></td>
		<td><%= link_to "Show", post_path(post), remote: true, class: "btn btn-primary"  %></td>
           
    </tr>
	
<% end %>

app/views/posts/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3> New Post</h3>
    </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/_save.js.erb
$("ul.errors").html("")
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |message| %>
	$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
    $(".post-index").html("<%= escape_javascript(render 'index') %>")
    $("#post-modal").modal("hide")
<% end %>    

app/views/posts/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
    <h3>
      <%= @post.title %>
    </h3>
    <h4>
      <%= @post.author %> 
    </h4>
    <h5>
      <%= @post.category.cat_name %>
    </h5>
    </div>
    <div class="modal-body">
      <%= @post.body %><br>
      <%= link_to '+', like_post_path(@post), remote: true %>
      <%= @post.rating %>
      <%= link_to '-', dislike_post_path(@post), remote: true %><br>

      <div class="modal-body">
      <div id='comments'>
      <%= render @post.comments %>      
      </div>
      </div>
      
      <%= render 'comments/form' %>


    </div>
    <div class="modal-footer">
      <%= link_to "Close", '#', class: "btn btn-danger", data: {dismiss: "modal"} %>
    </div>
</div>
</div>

app/views/posts/delete.js.erb
$("#post-modal").html("<%= escape_javascript(render 'delete') %>")
$("#post-modal").modal("show")

app/views/posts/edit.js.erb
$('#post-modal').html("<%= escape_javascript(render 'edit') %>");
$('#post-modal').modal("show");

app/views/posts/index.html.erb
<div class="container">
<div class="well">
    
    <%= link_to "New Post", new_post_path, remote: true, class: "btn btn-primary" %>
    <%= link_to "Category Manager", categories_path, class: "btn btn-primary" %>
   
</div>
<div class="new-post"></div>

<table class="table table-bordered table-striped">
  <thead>
  	<tr>
  		<th>Author</th>
      <th>Title</th>
  		<th>Body</th>
      <th>Rating</th>
      <th>Category</th>
  		<th>&nbsp;</th>
  		<th>&nbsp;</th>
    </tr>
  </thead>
  <tbody class="post-index">
  	<%= render 'index' %>
  </tbody>
</table>
</div>
<div id="post-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true"></div>

app/views/posts/new.js.erb

$('#post-modal').html("<%= escape_javascript(render 'new') %>");
$('#post-modal').modal("show");

app/views/posts/show.js.erb
$('#post-modal').html("<%= escape_javascript(render 'show') %>");
$('#post-modal').modal('show');